/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.14
 * Generated at: 2017-04-22 10:15:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html><head><title>회원가입 폼</title>\r\n");
      out.write("</head><body>\r\n");
      out.write("<center>\r\n");
      out.write("<form action=\"joinInsert_ok.jsp\" method=\"post\">\r\n");
      out.write("<table border=1>\r\n");
      out.write("<tr>\r\n");
      out.write("     <td align=right><font size=2>아이디 : </font></td>\r\n");
      out.write("     <td><input type=\"text\" name=\"id\"></td>  </tr>\r\n");
      out.write("<tr>\r\n");
      out.write("     <td align=right><font size=2>비밀번호 : </font></td>\r\n");
      out.write("     <td><input type=\"password\" name=\"pass\"></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("     <td align=right><font size=2>이름 : </font></td>\r\n");
      out.write("     <td><input type=\"text\" name=\"name\"></td></tr>\r\n");
      out.write("<tr> <td align=right><font size=2>성별 : </font></td>\r\n");
      out.write("      <td>\r\n");
      out.write("           <input type=\"radio\" name=\"sex\" value=\"남자\" checked>\r\n");
      out.write("                 <font size=2>남자</font>\r\n");
      out.write("      <input type=\"radio\" name=\"sex\" value=\"여자\"><font size=2>여자\r\n");
      out.write("                </font>    </td> </tr>\r\n");
      out.write("<tr> <td align=right><font size=2>나이 : </font></td>\r\n");
      out.write("        <td><input type=\"text\" name=\"age\"></td> </tr>\r\n");
      out.write("<tr> <td align=right><font size=2>이메일주소 : \r\n");
      out.write("              </font></td>\r\n");
      out.write("       <td><input type=\"text\" name=\"email\"></td>  </tr>\r\n");
      out.write("<tr> <td align=center colspan=2>\r\n");
      out.write("        <input type=\"submit\" value=\"가입\">\r\n");
      out.write("        <input type=\"reset\" value=\"다시 작성\">   </td>   </tr>\r\n");
      out.write("</table></form></center></body></html>\r\n");
      out.write("\r\n");
      out.write("     ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
